language: rust
os: linux
dist: trusty
sudo: require

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  - LIBVIRT=1.2.0  EXT=gz
  - LIBVIRT=1.2.10 EXT=gz
  - LIBVIRT=1.2.20 EXT=gz
  - LIBVIRT=2.5.0  EXT=xz
  - LIBVIRT=3.3.0  EXT=xz

install:
  - sudo apt-get -qqy build-dep libvirt
  - sudo apt-get -qqy install curl qemu-system-x86 sasl2-bin
  - sudo mkdir -p /usr/src && sudo chown $(id -u) /usr/src
  - curl -O -s https://libvirt.org/sources/libvirt-${LIBVIRT}.tar.${EXT}
  - tar -C /usr/src -xf libvirt-${LIBVIRT}.tar.${EXT}
  - pushd /usr/src/libvirt-${LIBVIRT}
  - |
        ./configure --prefix=/usr --localstatedir=/var --sysconfdir=/etc \
                    --without-polkit \
                    --without-esx --without-vbox --without-xen --without-libxl \
                    --with-qemu --with-lxc
  - make
  - sudo make install
  - popd
  - sudo libvirtd -d -l -f tests/libvirtd.conf
  - sudo virtlogd -d || true
  - sudo chmod a+rwx /var/run/libvirt/libvirt-sock*
  - echo "pass" | sudo saslpasswd2 -p -a libvirt user

script:
  - cargo test --verbose
  - cargo test --verbose -- --ignored
